import request from '@/utils/request'

/**
 * Detect if a domain is generated by DGA (Domain Generation Algorithm)
 * @param {string} url - The domain to check
 * Note: This endpoint may be disabled on the backend
 */
export function detectDGA(url) {
  return request({
    url: '/api/detect',
    method: 'post',
    data: { url }
  })
}
